[General]
  snippetfile = "~/.config/pet/snippet.toml"
  editor = "code --wait --new-window"
  column = 40
  selectcmd = "~/.dotfiles/lib/pet-preview.sh"
  backend = "gist"
  sortby = "description"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  public = false
  auto_sync = true

[GitLab]
  file_name = "pet-snippet.toml"
  access_token = ""
  url = ""
  id = ""
  visibility = "private"
  auto_sync = false
