[General]
  snippetfile = "~/.config/pet/snippet.toml"
  editor = "code --wait --new-window"
  column = 40
  selectcmd = "fzf --ansi --height 15% --layout reverse --prompt '? '"
  backend = "gist"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  public = false
  auto_sync = false

[GitLab]
  file_name = "pet-snippet.toml"
  access_token = ""
  url = ""
  id = ""
  visibility = "private"
  auto_sync = false
