#!/usr/bin/env zsh

apply_titlebar_colors() {
  printf "\033]6;1;bg;red;brightness;%d\a" 40
  printf "\033]6;1;bg;green;brightness;%d\a" 44
  printf "\033]6;1;bg;blue;brightness;%d\a" 52
}

reset_titlebar_colors() {
  printf "\033]6;1;bg;*;default\a"
}