#!/usr/bin/env bash

# Toggle hidden files in Finder
__macos_finder_toggle_hidden() {
  local on_off

  if [[ "$(defaults read com.apple.finder AppleShowAllFiles)" == "1" ]]; then
    on_off=false
  else
    on_off=true
  fi

  defaults write com.apple.finder AppleShowAllFiles -bool "$on_off" && \
    killall Finder
}

alias finder-show="__macos_finder_toggle_hidden"


# Fix font smoothing & dark mode on macOS Mojave on some apps
# https://reddit.com/r/apple/comments/9leavs/fix_mojave_font_rendering_issues_on_a_perapp_basis
# https://github.com/Microsoft/vscode/issues/59887#issuecomment-449636774
# https://apple.stackexchange.com/questions/102452/can-i-undo-changes-made-via-defaults-write
# https://www.reddit.com/r/apple/comments/9jr2zy/how_to_enable_mojave_dark_mode_for_applications/

function macos::defaults::set_bool {
  local bundle_id="$1"
  local setting_key="$2"
  local setting_value="$3"

  set -x
  defaults write "$bundle_id" "$setting_key" -bool "$setting_value"
  { set +x ; } 2>/dev/null
}
function macos::defaults::set_true {
  macos::defaults::set_bool "$1" "$2" YES
}
function macos::defaults::set_false {
  macos::defaults::set_bool "$1" "$2" NO
}
function macos::defaults::read {
  printf '"%s" = %s \n\n' "$1" "$1"
}
function macos::defaults::delete {
  local bundle_id="$1"
  local setting_key="$2"

  set -x
  defaults delete "$bundle_id" "$setting_key"
  { set +x ; } 2>/dev/null
}
function macos::defaults::exists {
  # Checks that the given domain exists, using fixed strings -- not regexes.
  #     macos::defaults::exists "foo.bar.FizzBuzz"    =>  true
  #     macos::defaults::exists "foo\.bar\.FizzBuzz"  =>  false
  defaults domains | rg --quiet --fixed-strings "$1"
}
function macos::defaults::fix_mojave {
  if ( macos::defaults::exists "com.microsoft.VSCode" ); then
    macos::defaults::read "com.microsoft.VSCode"

    # Use darkmode fix for vscode
    # macos::defaults::set_false "com.microsoft.VSCode" "NSRequiresAquaSystemAppearance"

    # Use font-smoothing fix for vscode
    macos::defaults::set_false "com.microsoft.VSCode" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::set_false "com.microsoft.VSCode.helper" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::set_false "com.microsoft.VSCode.helper.EH" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::set_false "com.microsoft.VSCode.helper.NP" "CGFontRenderingFontSmoothingDisabled"
  fi

  if ( macos::defaults::exists "com.microsoft.VSCodeInsiders" ); then
    macos::defaults::read "com.microsoft.VSCodeInsiders"

    # Use font-smoothing fix for vscode-insiders
    macos::defaults::set_false "com.microsoft.VSCodeInsiders" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::set_false "com.microsoft.VSCodeInsiders.helper" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::set_false "com.microsoft.VSCodeInsiders.helper.EH" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::set_false "com.microsoft.VSCodeInsiders.helper.NP" "CGFontRenderingFontSmoothingDisabled"
  fi

  if ( macos::defaults::exists "com.spotify.client" ); then
    macos::defaults::read "com.spotify.client"

    # Use font-smoothing fix for spotify
    macos::defaults::set_false "com.spotify.client" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::set_false "com.spotify.client.helper" "CGFontRenderingFontSmoothingDisabled"
  fi
}
function macos::defaults::unfix_mojave {
  if ( macos::defaults::exists "com.microsoft.VSCode" ); then
    macos::defaults::read "com.microsoft.VSCode"

    # Use darkmode fix for vscode
    # macos::defaults::delete "com.microsoft.VSCode" "NSRequiresAquaSystemAppearance"

    # Use font-smoothing fix for vscode
    macos::defaults::delete "com.microsoft.VSCode" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::delete "com.microsoft.VSCode.helper" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::delete "com.microsoft.VSCode.helper.EH" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::delete "com.microsoft.VSCode.helper.NP" "CGFontRenderingFontSmoothingDisabled"
  fi

  if ( macos::defaults::exists "com.microsoft.VSCodeInsiders" ); then
    macos::defaults::read "com.microsoft.VSCodeInsiders"

    # Use font-smoothing fix for vscode-insiders
    macos::defaults::delete "com.microsoft.VSCodeInsiders" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::delete "com.microsoft.VSCodeInsiders.helper" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::delete "com.microsoft.VSCodeInsiders.helper.EH" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::delete "com.microsoft.VSCodeInsiders.helper.NP" "CGFontRenderingFontSmoothingDisabled"
  fi

  if ( macos::defaults::exists "com.spotify.client" ); then
    macos::defaults::read "com.spotify.client"

    # Use font-smoothing fix for spotify
    macos::defaults::delete "com.spotify.client" "CGFontRenderingFontSmoothingDisabled"
    macos::defaults::delete "com.spotify.client.helper" "CGFontRenderingFontSmoothingDisabled"
  fi
}
